"""
One-time offline training script for the Routine/game difficulty-adaptation
model. NOT a runtime dependency — run manually, commit the resulting weights
JSON, and re-run only if you want to retrain.

BOOTSTRAP DISCLOSURE (read before trusting this model's outputs):
There is no clinically-validated ground truth for "should difficulty go up,
down, or stay the same." The label used here is generated by re-simulating
the EXACT decision the app's existing rule-based streak counter
(src/lib/engine/difficulty.ts) would make, applied session-by-session across
thousands of synthetic patient histories. The model therefore learns to
approximate that rule engine, not some external truth — it is a
first-generation bootstrap, not a clinically superior replacement. Its
practical value is that it can weigh four extra signals (reaction-time
z-score, error streak, domain accuracy, session fatigue) that the rule engine
never looks at at all, so it can diverge usefully from the rule engine
specifically in sessions where raw accuracy alone is a misleading summary
(e.g. accurate-but-fatiguing, or accurate-with-late-error-streak).

Requires: pip install scikit-learn numpy (dev-only, not shipped).
"""

import json
import random
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression

RNG = random.Random(42)
NP_RNG = np.random.default_rng(42)

# Mirrors src/lib/engine/difficulty.ts exactly.
HIGH_THRESHOLD = 80.0
LOW_THRESHOLD = 50.0
HIGH_STREAK_TO_LEVEL_UP = 3
LOW_STREAK_TO_LEVEL_DOWN = 2
MIN_LEVEL = 1
MAX_LEVEL = 10  # generic ceiling for training purposes; per-game ceilings vary at runtime

CLASSES = ["decrease", "maintain", "increase"]


def rule_engine_step(level, high_streak, low_streak, session_accuracy):
    """Reimplementation of adjustDifficulty()'s branch logic — the label oracle."""
    if session_accuracy >= HIGH_THRESHOLD:
        high_streak += 1
        if high_streak >= HIGH_STREAK_TO_LEVEL_UP:
            return min(MAX_LEVEL, level + 1), 0, 0, "increase"
        return level, high_streak, 0, "maintain"

    if session_accuracy < LOW_THRESHOLD:
        low_streak += 1
        if low_streak >= LOW_STREAK_TO_LEVEL_DOWN:
            return max(MIN_LEVEL, level - 1), 0, 0, "decrease"
        return level, 0, low_streak, "maintain"

    return level, 0, 0, "maintain"


def simulate_session(true_skill, round_count):
    """
    Generates one synthetic session's round-by-round correctness and reaction
    times. `true_skill` in [0,1] sets the base accuracy; a within-session
    fatigue drift lowers accuracy and slows reaction time in later rounds,
    the noisy proxy the app's own session_fatigue feature is meant to catch.
    """
    correct = []
    rt_ms = []
    for round_idx in range(round_count):
        fatigue = round_idx / max(1, round_count - 1)  # 0 -> 1 across the session
        p_correct = np.clip(true_skill - 0.15 * fatigue + NP_RNG.normal(0, 0.05), 0.02, 0.98)
        is_correct = NP_RNG.random() < p_correct
        correct.append(bool(is_correct))
        base_rt = 1800 - 900 * true_skill
        rt = base_rt * (1 + 0.4 * fatigue) + NP_RNG.normal(0, 150)
        rt_ms.append(max(200, rt))
    return correct, rt_ms


def extract_features(correct, rt_ms):
    """Must match the feature computation in src/lib/games/difficulty-ml.ts exactly."""
    n = len(correct)
    last5 = correct[-5:]
    rolling_accuracy = sum(last5) / len(last5)

    mean_rt = float(np.mean(rt_ms))
    std_rt = float(np.std(rt_ms))
    reaction_time_zscore = 0.0 if std_rt < 1e-6 else (rt_ms[-1] - mean_rt) / std_rt

    error_streak = 0
    for c in reversed(correct):
        if c:
            break
        error_streak += 1

    domain_accuracy = sum(correct) / n

    session_fatigue = min(n, 20) / 20.0

    return [rolling_accuracy, reaction_time_zscore, error_streak, domain_accuracy, session_fatigue]


def generate_dataset(n_patients=400, sessions_per_patient=25):
    X, y = [], []
    for _ in range(n_patients):
        level, high_streak, low_streak = RNG.randint(1, 5), 0, 0
        true_skill = np.clip(NP_RNG.normal(0.6, 0.15), 0.1, 0.95)

        for _ in range(sessions_per_patient):
            true_skill = np.clip(true_skill + NP_RNG.normal(0, 0.03), 0.05, 0.98)
            round_count = RNG.randint(5, 20)
            correct, rt_ms = simulate_session(true_skill, round_count)
            session_accuracy = 100.0 * sum(correct) / len(correct)

            features = extract_features(correct, rt_ms)
            level, high_streak, low_streak, label = rule_engine_step(
                level, high_streak, low_streak, session_accuracy
            )

            X.append(features)
            y.append(label)

    return np.array(X), np.array(y)


def main():
    X, y = generate_dataset()
    print(f"Generated {len(X)} labeled sessions. Class balance: "
          f"{ {c: int((y == c).sum()) for c in CLASSES} }")

    # sklearn >=1.7 dropped the `multi_class` kwarg — lbfgs now always fits a
    # genuine multinomial (softmax) model for a >2-class target automatically.
    # class_weight="balanced" matters here: "increase" is a rare label (the
    # rule oracle only emits it on the 3rd consecutive high-accuracy
    # session), and an unweighted fit lets "maintain" dominate the softmax
    # for every high-accuracy feature vector, effectively never predicting
    # "increase" at all regardless of input.
    model = LogisticRegression(solver="lbfgs", max_iter=1000, class_weight="balanced")
    model.fit(X, y)

    train_acc = model.score(X, y)
    print(f"Training-set accuracy vs. the rule-engine oracle: {train_acc:.3f}")

    # sklearn orders classes_ alphabetically: decrease, increase, maintain —
    # remap rows to CLASSES' fixed order so the JSON and JS agree unambiguously.
    class_order = list(model.classes_)
    row_for = [class_order.index(c) for c in CLASSES]

    weights = {
        "classes": CLASSES,
        "featureNames": [
            "rolling_accuracy",
            "reaction_time_zscore",
            "error_streak",
            "domain_accuracy",
            "session_fatigue",
        ],
        "coefficients": [model.coef_[i].tolist() for i in row_for],
        "intercepts": [float(model.intercept_[i]) for i in row_for],
        "trainingAccuracyVsRuleOracle": round(float(train_acc), 4),
        "note": "Bootstrapped from the rule-based streak engine on synthetic sessions. See docstring at the top of this script.",
    }

    out_path = Path(__file__).resolve().parent.parent / "src" / "lib" / "games" / "difficulty-model-weights.json"
    out_path.write_text(json.dumps(weights, indent=2) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
