import { createBrowserClient as createSSRBrowserClient, createServerClient as createSSRServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';
import type { CookieOptions } from '@supabase/ssr';
import type { Database } from './types';

/**
 * Supabase client factories.
 *
 * Environment variables are read inside the factories rather than at module
 * scope. SMRITI prerenders 18 routes at build time, and a module-scope read
 * would throw during the build on any machine without a .env.local.
 */

function readEnv(): { url: string; anonKey: string } {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!url || !anonKey) {
    throw new Error(
      'Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL and ' +
        'NEXT_PUBLIC_SUPABASE_ANON_KEY (see .env.local.example). SMRITI games ' +
        'and reminders work offline without these; only sync and the caregiver ' +
        'dashboard require them.',
    );
  }
  return { url, anonKey };
}

/** True when Supabase credentials are present. Lets callers degrade to offline-only. */
export function isSupabaseConfigured(): boolean {
  return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
}

/**
 * Service-role client — bypasses RLS entirely. Server-only, and only for
 * routes that have already authorized the caller themselves (e.g. validating
 * a kiosk device-trust token, which has no Supabase session for RLS to key
 * off). Never import this from client code; the key must never reach the
 * browser bundle.
 */
export function createServiceRoleClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    throw new Error('Supabase service role is not configured. Set SUPABASE_SERVICE_ROLE_KEY.');
  }
  return createClient<Database>(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

/**
 * Browser client for Client Components.
 *
 * Always PKCE — `@supabase/ssr`'s `createBrowserClient` hardcodes
 * `flowType: 'pkce'` *after* spreading any `auth` options passed in
 * (see its source: `{...options?.auth, flowType: 'pkce', ...}`), so an
 * override here is silently discarded. Session reads/writes throughout the
 * app (caregiver layout, sync, etc.) all go through this client and its
 * cookie-based session — that's what actually needs to stay consistent.
 * For the one place that needs implicit flow instead (sending the login
 * magic link, so it doesn't depend on this same browser's storage still
 * being around when the link is clicked), see `createLoginLinkClient` below.
 */
export function createBrowserClient() {
  const { url, anonKey } = readEnv();
  return createSSRBrowserClient<Database>(url, anonKey);
}

/**
 * A separate, throwaway client used only to call `signInWithOtp` when
 * sending the caregiver login link — never for reading or storing a
 * session (`persistSession: false`, `detectSessionInUrl: false`).
 *
 * `@supabase/ssr`'s `createBrowserClient` cannot be used for this: it
 * hardcodes `flowType: 'pkce'` unconditionally (see the comment above), so
 * every magic link it requests comes back as `?code=...`, needing the
 * exact code verifier this browser generated to still be in its storage
 * when the link is clicked — which breaks the instant the link is opened
 * in a different browser/app (a caregiver's email app opening it in its
 * own in-app browser, most commonly), surfacing as "PKCE code verifier not
 * found in storage." Calling `signInWithOtp` through a plain
 * `@supabase/supabase-js` client with `flowType: 'implicit'` instead makes
 * Supabase mint a link that returns the session tokens directly in the
 * redirect URL's hash fragment — openable from any browser, no stored
 * verifier required. `caregiver/login/callback/page.tsx` already handles
 * that hash shape (built for the admin-generated bypass link, which never
 * went through PKCE either) and calls `.setSession()` on the *normal*
 * `createBrowserClient()` above, so the real session still ends up in the
 * same cookie storage everything else reads from.
 */
export function createLoginLinkClient() {
  const { url, anonKey } = readEnv();
  return createClient<Database>(url, anonKey, {
    auth: { flowType: 'implicit', persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });
}

/**
 * Server client for Route Handlers and Server Components.
 *
 * `cookies()` from `next/headers` is async in Next 16, so the caller passes the
 * resolved cookie store in:
 *
 *   import { cookies } from 'next/headers';
 *   const supabase = createServerClient(await cookies());
 *
 * Server Components cannot write cookies; the setAll failure is swallowed
 * there, which is safe when middleware refreshes the session.
 */
export function createServerClient(
  cookieStore: {
    getAll(): { name: string; value: string }[];
    set(name: string, value: string, options?: CookieOptions): void;
  },
  options?: { authorization?: string },
) {
  const { url, anonKey } = readEnv();

  return createSSRServerClient<Database>(url, anonKey, {
    // API routes authenticate via Bearer token, not the cookie session — this
    // makes RLS see the caller's identity on every `.from()` query too.
    global: options?.authorization
      ? { headers: { Authorization: options.authorization } }
      : undefined,
    cookies: {
      getAll() {
        return cookieStore.getAll();
      },
      setAll(cookiesToSet) {
        try {
          for (const { name, value, options: cookieOptions } of cookiesToSet) {
            cookieStore.set(name, value, cookieOptions);
          }
        } catch {
          // Called from a Server Component, which cannot set cookies.
          // Middleware is responsible for refreshing the session instead.
        }
      },
    },
  });
}
